# Generated by Django 4.2.17 on 2025-11-26 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_rest_opaque", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opaquecredential",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opaque_credential",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
