# Generated by Django 4.2.17 on 2025-12-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
